### ISSUE TITLE
MetEx (Mutilple) mode issue

### ISSUE THREAD

**Issue by g0079** [zhengfj1994/MetEx#1]
Hi all,
When I run  `shiny::runApp(system.file("extdata/shinyApp", package = "MetEx"))` , I can only find the following GUI
![image](https://user-images.githubusercontent.com/92711500/190958654-44d802a1-4a2f-4cf3-b580-da0046bfbad5.png)
and the I don't see the MetEx (Mutilple) option. Do I miss something important to show the MetEx (Mutilple) option? It would be really appreciated if this question could be answered.

**Comment by zhengfj1994** [comment]
Hi：
I'm the maintainer of MetEx project. MetEx (Mutilple) was temporarily hidden because I think it lacks sufficient testing. In fact, it still exists in the source code. I will improve MetEx (Mutilple) and release it. It will take some times. I will complete this part as soon as possible. (Maybe in one week, you can continue to pay attention to MetEx). I apologize for your inconvenience caused due to my limited energy.

**Comment by g0079** [comment]
Thank you for quick reply. Hope you will do a good work @zhengfj1994

**Comment by zhengfj1994** [comment]
Hi:
I upgraded MetEx to v1.4.0. Now, run shiny::runApp(system.file("extdata/shinyApp", package = "MetEx")), MetEx (Mutilple) option is available in MetEx v1.4.0
![image](https://user-images.githubusercontent.com/34928125/191239376-54923d7a-04ce-4cec-97dd-c88e222df750.png)
